language: node_js
node_js:
- 7.3.0
notifications:
  slack:
    secure: Epn3esGQ+CvBcyi/4bUggvvtG/9LidBbh7URs2h5t9yl2tuom4hpW3yhIhPKGCLhqfzkpQMgD2hNom1H3bjGWqodUUFkdRkLz74GX2SuDeV0Zuzt73ct5wPGJIKd6Wo4O0amEbwwgNTtoiHE0LzM7GU4q820xZFCYLIJjoDbj1w0hEZTsA22ED+cpSHLKFdYlUVc6SDDaKORmp+d7h+XXFoUmn+G3m6y+andMC6yHTPX1iWgpl4Ns3W1+q1IyUwA3/A5j5Kk1+Y+pRpU5eiCwfXkR31aM+QY5bfQkZzA11UrAxVLnAuO8KgxaH7D+cNU2Qk24Q8gRniiAomIFhIyjybD1gLgxPo4I1eAvIuoTbm7THBHnLQZ+GTBycG0tVmSzjHKUlNTAZrhYmkxlTaGWnOm9IP9exUvy/z90nP1IuP2ZRzGzTLJBav2Tqi2jQcoakgzSi8Sz2rLB+SVmelFu/ACKVURzOpW3Isj4GZetnd2oo2X2XfLcr3HuYAS3S4CSk64pVY7gAlYVnHFcW5ohdmgvs7G199boQbz9afAqb1BzYsRtfi5NMOiYmfZavLPZK2BCEdRBeKFZAs0g048SApYNkFClVUv3JXlFBZ1AJmkpQM89ns5G0tOfiYLsRM7LDzg91wIKzKa4xum/Aof7SBWZE3oF8CQb7gmuDdJtzA=
